name: in_app_notification
description: A Flutter package to show custom in-app notification with any Widgets.
version: 1.0.1
repository: https://github.com/cb-cloud/flutter_in_app_notification

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter: